### ISSUE TITLE
Link for design is not accessible

### ISSUE THREAD

**Issue by alynioke** [Vidmasas/lint#30]
Link in [README](https://github.com/Vidmapps/lint/blob/master/README.md#lint) leads to Zeplin - first you should register, then you should be invited to project, and only then you can see design. That is inconvenient.
I suggest making design accessible with 1 click for anyone  (no need to register, be invited, etc) - if project is public on github, then link should be too.

**Comment by Vidmapps** [comment]
Good point, I have checked and it seems it can be reached publicly (there are no settings to allow this). I will put the link to the work files then not the project design. What do you think? https://www.sketchappsources.com/free-source/3987-lint-web-dashboard-dark-sketch-freebie-resource.html

**Comment by alynioke** [comment]
I tried this link - 
1) clicking on link
2) clicking download
3) unzipping project
4) clicking on file and getting message 
![image](https://user-images.githubusercontent.com/528887/81091770-59f59b00-8f08-11ea-8610-48286c1095ec.png)

oops 😄 

Perhaps you can download this file, convert to png/jpeg, upload it to GDrive or Dropbox (depends what you have), and just provide link to it? it will be 1 click only then :) a bit more work for you, but then no work for whoever gonna be checking your repo. I think it's important, since you recently mentioned you want to put it in portfolio.

**Comment by alynioke** [comment]
solved
